<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net10.0</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Ast.fs" />
    <Compile Include="Lexer.fs" />
    <Compile Include="ParserSimple.fs" />
    <Compile Include="Validator.fs" />
    <Compile Include="Values.fs" />
    <Compile Include="Builtins.fs" />
    <Compile Include="Bytecode.fs" />
    <Compile Include="Compiler.fs" />
    <Compile Include="StackVm.fs" />
    <Compile Include="FsVb.fs" />
  </ItemGroup>

</Project>
